### ISSUE TITLE
Highly recommend against suggesting a NOHUP for gulp.

### ISSUE THREAD

**Issue by Qix-** [accommodavid/spooky-react#3]
In your readme it states you should use `gulp &`. One can only assume it's because the default task is to watch files or something, and `&` is assumed to be a clever way to stick the watch in the background.

Using `&` is a surefire way to mess developers up who don't know what they're doing; not only will you receive a bunch of issues here, they will spill over to `gulp`, too. Further, if someone closes their shell and re-opens it later to go back to run the same command that watches and doesn't hangup, then they're going to be building twice which could potentially throw the build into an infinite loop or make the systems refuse to build at all.

Why not just `gulp`?

**Comment by accommodavid** [comment]
Could you explain in more detail how it could mess things up? As far as I know, I'm just spawning a child process here. When the shell is exited, the child process is killed. To produce the issue you describe, I'd explicitly have to do `nohup gulp &`.

**Comment by Qix-** [comment]
[This SO answer](http://stackoverflow.com/a/15595391) describes a scenario where that isn't the case; namely, bash users (which, as you probably know, there are a _lot_ of bash users). If the shell doesn't send the SIGHUP then the process won't be terminated. All nohup does is runs a child process and wraps it with a signal handler for SIGHUP that silences it. If the shell doesn't send SIGHUP to begin with, then child processes that are started with `&` will never receive the signal to hang up.

I see I did make a slight mistake in my OP; I've fixed it.

**Comment by accommodavid** [comment]
Ah, I see. I'm not able to reproduce on OS X 10.11 and Ubuntu 14.04.3. However, I do see it's not common practice, so I'm going to remove it from the README anyway. If anyone wants to use the functionality, I mean, nothing can stop them from adding the ampersand anyway.
